name: HotelBookingTest

on:
  workflow_dispatch

jobs:
  Build:
    name: Build Solution
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  Test:
    name: Run Tests
    runs-on: self-hosted
    needs: [Build]
    
    steps:
     - run: dotnet test ./test/HotelBooking.Test --no-build --no-restore --results-directory ".\TestResults\" --logger "trx;LogFileName=testResults.trx"

  PublishResults:
    name: Publish Test Results
    runs-on: self-hosted
    needs: [Test]
    
    steps:
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Booking Tests
          path: ./TestResults/testResults.trx
          reporter: dotnet-trx
